#!/bin/bash

if [ `whoami` != "gensys" ]
then
        echo "Ejecutame como usuario gensys"
        exit 1
fi

buildbot start /var/gensys/testsys/gecosmaster
cd /var/gensys/testsys/pkgbuilderbot; buildbot-worker start; cd ..
cd /var/gensys/testsys/gensysbot; buildbot-worker start; cd ..

