#!/bin/sh
set -e
# Automatically added by dh_installinit/11.1.6ubuntu2
if [ "$1" = "purge" ] ; then
	echo "update-rc.d ubiquity remove"
	yes | update-rc.d ubiquity remove >/dev/null
fi


# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
	echo "systemctl --system daemon-reload"
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_systemd_enable/11.1.6ubuntu2
if [ "$1" = "remove" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper mask 'ubiquity.service' >/dev/null || true
	fi
fi

if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		echo "deb-systemd-helper purge 'ubiquity.service'"
		yes | deb-systemd-helper purge 'ubiquity.service' >/dev/null || true
		echo "deb-systemd-helper unmark 'ubiquity.service'"
		yes | deb-systemd-helper unmask 'ubiquity.service' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installdebconf/11.1.6ubuntu2
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	echo "execute confmodule"
	. /usr/share/debconf/confmodulea
	echo "db_purge"
	db_purge
fi
# End automatically added section
echo "end"
