#!/bin/sh

PREREQ=""

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

if grep -q integrity-check /proc/cmdline; then
	casper-md5check /cdrom /cdrom/MD5SUMS < /dev/tty1 > /dev/tty1
fi
